export {
    MEDICATION_URGENCY_CRITICAL_MAX_DAYS as MEDICATION_SUPPLY_CRITICAL_MAX_DAYS,
    MEDICATION_URGENCY_PROGRESS_FULL_DAYS as MEDICATION_SUPPLY_PROGRESS_FULL_DAYS,
    MEDICATION_URGENCY_WARNING_MAX_DAYS as MEDICATION_SUPPLY_WARNING_MAX_DAYS,
} from '@/lib/patient/medications/urgency/medicationUrgencyThresholds';
