export const MEDICATION_URGENCY_CRITICAL_MAX_DAYS = 7;

export const MEDICATION_URGENCY_WARNING_MAX_DAYS = 14;

export const MEDICATION_URGENCY_PROGRESS_FULL_DAYS =
    MEDICATION_URGENCY_WARNING_MAX_DAYS;
